[package]
name = "duma"
version = "0.1.0"
authors = ["Matt Gathu <mattgathu@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.11"
indicatif = "0.11.0"
console = "0.7.5"
clap = "2.31.2"
ftp = "3.0.1"
threadpool = "1.7.1"
failure = "0.1.2"

[dev-dependencies]
assert_cli = "0.4"
