[package]
name = "duma"
version = "0.1.0"
authors = ["Matt Gathu <mattgathu@gmail.com>"]
edition = "2018"

[dependencies]
indicatif = "0.11.0"
console = "0.7.5"
clap = "2.31.2"
ftp = "3.0.1"
threadpool = "1.7.1"
failure = { version = "0.1.5", features = [] }
minreq = {git = "https://github.com/mattgathu/minreq/", branch = "duma", features = ["https"]}
url = "1.7.2"

[dev-dependencies]
assert_cmd = "0.11"
